collections:
    maps:
        output: true
        permalink: /:name

defaults:
    - 
      scope:
        path: ""
        type: "maps"
      values:
        layout: "maps"

baseurl: "/CommunityMaps"